### ISSUE TITLE
Providing PDB file instead of CCMPRED breaks app

### ISSUE THREAD

**Issue by FilomenoSanchez** [rigdenlab/conplot#116]
**Describe the bug**
If the user selects to upload a CCMPRED contact map but a PDB file is provided instead, the app breaks

**To Reproduce**
1. Go to 'Plot'
2. Select CCMPRED format
3. Upload PDB file
4. App breaks

**Expected behavior**
A modal should be displayed to inform the user the file is not valid

**Additional context**
```python
Traceback (most recent call last):
  File "/home/filo/PycharmProjects/conplot/app.py", line 335, in upload_contact
    return data_utils.upload_dataset(fname, fcontent, input_format, fname_alerts, session_id, cache, app.logger,
  File "/home/filo/PycharmProjects/conplot/utils/data_utils.py", line 39, in upload_dataset
    data, invalid = loaders.Loader(fcontent, input_format)
  File "/home/filo/PycharmProjects/conplot/loaders/__init__.py", line 39, in Loader
    return Loader(*args, **kwargs)
  File "/home/filo/PycharmProjects/conplot/loaders/loader.py", line 18, in Loader
    data_raw = ParserFormats.__dict__[input_format](decoded)
  File "/home/filo/PycharmProjects/conplot/parsers/__init__.py", line 37, in CCMpredParser
    return CCMpredParser(*args, **kwargs)
  File "/home/filo/PycharmProjects/conplot/parsers/ccmpredparser.py", line 17, in CCMpredParser
    raw_score = float(raw_score)
ValueError: could not convert string to float: 'CRYST1'
```

**Comment by FilomenoSanchez** [comment]
Closed by #117
