### ISSUE TITLE
Missing required input warning modal is not displayed

### ISSUE THREAD

**Issue by FilomenoSanchez** [rigdenlab/conplot#47]
**Describe the bug**
If the user does not upload required data (contact map and/or sequence), nothing occurs upon clicking on 'Generate Plot'.

**To Reproduce**
1. Go to 'Plot'
2. Click on 'Generate Plot'
3. Nothing occurs

**Expected behavior**
A modal warning should be displayed informing the user that there is missing required data

**Traceback**
```python
 Traceback (most recent call last):
   File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
     response = self.full_dispatch_request()
   File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
     rv = self.handle_user_exception(e)
   File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
     reraise(exc_type, exc_value, tb)
   File "/app/.heroku/python/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
     raise value
   File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
     rv = self.dispatch_request()
   File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
     return self.view_functions[rule.endpoint](**req.view_args)
   File "/app/.heroku/python/lib/python3.6/site-packages/dash/dash.py", line 967, in dispatch
     response.set_data(func(*args, outputs_list=outputs_list))
   File "/app/.heroku/python/lib/python3.6/site-packages/dash/dash.py", line 902, in add_context
     output_value = func(*args, **kwargs)  # %% callback invoked %%
   File "/app/app.py", line 329, in create_ConPlot
     track_separation)
   File "/app/utils/plot_utils.py", line 49, in create_ConPlot
     track_marker_size, track_separation = process_args(**locals())
   File "/app/utils/plot_utils.py", line 122, in process_args
     seq_lenght = len(session[DatasetReference.SEQUENCE.value.encode()])
```

**Comment by FilomenoSanchez** [comment]
Closed with 7c62a8f36060cfdbf9b9392afe42c869deaedac3
